[2023-08-31T04:02:30.756+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_sale_data.validate_result manual__2023-08-31T04:02:23.005684+00:00 [queued]>
[2023-08-31T04:02:30.766+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_sale_data.validate_result manual__2023-08-31T04:02:23.005684+00:00 [queued]>
[2023-08-31T04:02:30.766+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-31T04:02:30.779+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): validate_result> on 2023-08-31 04:02:23.005684+00:00
[2023-08-31T04:02:30.787+0000] {standard_task_runner.py:57} INFO - Started process 6201 to run task
[2023-08-31T04:02:30.790+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'process_sale_data', 'validate_result', 'manual__2023-08-31T04:02:23.005684+00:00', '--job-id', '190', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmpgs58rbdp']
[2023-08-31T04:02:30.792+0000] {standard_task_runner.py:85} INFO - Job 190: Subtask validate_result
[2023-08-31T04:02:30.838+0000] {task_command.py:410} INFO - Running <TaskInstance: process_sale_data.validate_result manual__2023-08-31T04:02:23.005684+00:00 [running]> on host 888526fa4a36
[2023-08-31T04:02:30.933+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_sale_data' AIRFLOW_CTX_TASK_ID='validate_result' AIRFLOW_CTX_EXECUTION_DATE='2023-08-31T04:02:23.005684+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-31T04:02:23.005684+00:00'
[2023-08-31T04:02:31.082+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-08-31T04:02:31.086+0000] {sql.py:375} INFO - Running statement: SELECT COUNT(*) FROM consumption_alcoholic_20230831, parameters: None
[2023-08-31T04:02:31.087+0000] {sql.py:384} INFO - Rows affected: 1
[2023-08-31T04:02:31.100+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-08-31T04:02:31.103+0000] {sql.py:375} INFO - Running statement: SELECT COUNT(*) FROM consumption_cereals_bakery_20230831, parameters: None
[2023-08-31T04:02:31.105+0000] {sql.py:384} INFO - Rows affected: 1
[2023-08-31T04:02:31.110+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-08-31T04:02:31.121+0000] {sql.py:375} INFO - Running statement: SELECT COUNT(*) FROM consumption_meats_poultry_20230831, parameters: None
[2023-08-31T04:02:31.123+0000] {sql.py:384} INFO - Rows affected: 1
[2023-08-31T04:02:31.160+0000] {logging_mixin.py:149} INFO - Import data successful
[2023-08-31T04:02:31.160+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-08-31T04:02:31.173+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=process_sale_data, task_id=validate_result, execution_date=20230831T040223, start_date=20230831T040230, end_date=20230831T040231
[2023-08-31T04:02:31.203+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-08-31T04:02:31.228+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
