[2023-08-31T04:01:06.024+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_sale_data.validate_result manual__2023-08-31T04:01:00.587441+00:00 [queued]>
[2023-08-31T04:01:06.034+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_sale_data.validate_result manual__2023-08-31T04:01:00.587441+00:00 [queued]>
[2023-08-31T04:01:06.034+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-31T04:01:06.046+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): validate_result> on 2023-08-31 04:01:00.587441+00:00
[2023-08-31T04:01:06.053+0000] {standard_task_runner.py:57} INFO - Started process 6120 to run task
[2023-08-31T04:01:06.055+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'process_sale_data', 'validate_result', 'manual__2023-08-31T04:01:00.587441+00:00', '--job-id', '184', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmp8acbl92e']
[2023-08-31T04:01:06.057+0000] {standard_task_runner.py:85} INFO - Job 184: Subtask validate_result
[2023-08-31T04:01:06.097+0000] {task_command.py:410} INFO - Running <TaskInstance: process_sale_data.validate_result manual__2023-08-31T04:01:00.587441+00:00 [running]> on host 888526fa4a36
[2023-08-31T04:01:06.166+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_sale_data' AIRFLOW_CTX_TASK_ID='validate_result' AIRFLOW_CTX_EXECUTION_DATE='2023-08-31T04:01:00.587441+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-31T04:01:00.587441+00:00'
[2023-08-31T04:01:06.290+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-08-31T04:01:06.293+0000] {sql.py:375} INFO - Running statement: SELECT COUNT(*) FROM consumption_alcoholic_20230831, parameters: None
[2023-08-31T04:01:06.294+0000] {sql.py:384} INFO - Rows affected: 1
[2023-08-31T04:01:06.300+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-08-31T04:01:06.303+0000] {sql.py:375} INFO - Running statement: SELECT COUNT(*) FROM consumption_cereals_bakery_20230831, parameters: None
[2023-08-31T04:01:06.304+0000] {sql.py:384} INFO - Rows affected: 1
[2023-08-31T04:01:06.309+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-08-31T04:01:06.312+0000] {sql.py:375} INFO - Running statement: SELECT COUNT(*) FROM consumption_meats_poultry_20230831, parameters: None
[2023-08-31T04:01:06.313+0000] {sql.py:384} INFO - Rows affected: 1
[2023-08-31T04:01:06.336+0000] {logging_mixin.py:149} INFO - Import data successful
[2023-08-31T04:01:06.337+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-08-31T04:01:06.344+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=process_sale_data, task_id=validate_result, execution_date=20230831T040100, start_date=20230831T040106, end_date=20230831T040106
[2023-08-31T04:01:06.389+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-08-31T04:01:06.411+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
